src/myapp/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

from . import views

app_name = 'app'
urlpatterns = [

    url(r'^admin/members/$', login_required(views.MembersAdminView.as_view()), name='members-admin'),

	url(r'^$', login_required(views.index), name='index'),
    url(r'^home/$', login_required(views.home), name='home'),
    url(r'^members/$', login_required(views.MembersView.as_view()), name='members'),
    url(r'^resources/$', login_required(views.ResourcesView.as_view()), name='resources'),

    url(r'^vendors/$', login_required(views.VendorsView.as_view()), name='vendors'),
    url(r'^vendors/create/$', login_required(views.VendorCreateView.as_view()), name='vendor-create'),
    url(r'^vendors/update/(?P<pk>\d+)/$', login_required(views.VendorUpdateView.as_view()), name='vendor-update'),

    url(r'^jobs/$', login_required(views.JobsView.as_view()), name='jobs'),
    url(r'^jobs/create/$', login_required(views.JobCreateView.as_view()), name='job-create'),
    url(r'^jobs/update/(?P<pk>\d+)/$', login_required(views.JobUpdateView.as_view()), name='job-update'),

    url(r'^events/$', login_required(views.EventsView.as_view()), name='events'),
    url(r'^events/create/$', login_required(views.EventCreateView.as_view()), name='event-create'),
    url(r'^events/update/(?P<pk>\d+)/$', login_required(views.EventUpdateView.as_view()), name='event-update'),
    url(r'^members/(?P<username>[\w.@+-]+)/$', login_required(views.profile), name='profile'),
    url(r'^status/$', login_required(views.StatusView.as_view()), name='status'),
    
    url(r'^post/create/$', views.post_create, name='post_create'),
    url(r'^post/comment/create/$', views.comment_create, name='comment_create'),

    url(r'^accounts/info/$', login_required(views.InfoView.as_view()), name='info'),
    url(r'^accounts/info/update/(?P<pk>\d+)/$', login_required(views.InfoUpdateView.as_view()), name='info-update'),

    url(r'^api/delete/post/(?P<post_id>[0-9]+)',
        login_required(views.delete_post),
        name='delete-post'),
    url(r'^api/delete/comment/(?P<comment_id>[0-9]+)',
        login_required(views.delete_comment),
        name='delete-comment'),
    url(r'^api/delete/job/(?P<job_id>[0-9]+)',
        login_required(views.delete_job),
        name='delete-job'),
    url(r'^api/delete/event/(?P<event_id>[0-9]+)',
        login_required(views.delete_event),
        name='delete-event'),
    url(r'^api/delete/vendor/(?P<vendor_id>[0-9]+)',
        login_required(views.delete_vendor),
        name='delete-vendor'),
]

src/mydjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myapp.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^accounts/', include('allauth.urls')),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'myapp.views.not_found'
handler500 = 'myapp.views.server_error'
handler403 = 'myapp.views.permission_denied'
handler400 = 'myapp.views.bad_request'

src/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from pinax.eventlog.models import log
from datetime import datetime, timezone
from django.contrib.postgres.fields import ArrayField

class Team(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=300)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)

class TeamMember(models.Model):
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user)

class Feature(models.Model):
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    image = models.FileField(upload_to='images/%Y%m%d')
    text = models.TextField(blank=True)
    link = models.URLField(blank=True)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)


class Article(models.Model):
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    image = models.FileField(upload_to='images/%Y%m%d')
    text = models.TextField(blank=True)
    link = models.URLField(blank=True)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)

class Announcement(models.Model):
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    text = models.TextField(blank=True)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)

class Vendor(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=200)
    description = models.TextField()
    link = models.URLField(blank=True)
    categories = ArrayField(models.CharField(max_length=200))
    contact = models.CharField(max_length=500,blank=True)
    contact_email = models.CharField(max_length=500,blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)

    def __str__(self):
        return str(self.title)

class Event(models.Model):
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    description = models.TextField()
    location = models.CharField(max_length=300)
    link = models.URLField(blank=True)
    image = models.FileField(upload_to='images/%Y%m%d')
    datetime = models.DateTimeField()
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)

class Rsvp(models.Model):
    user = models.ForeignKey(User)
    event = models.ForeignKey(Event)

    def __str__(self):
        return str(self.user)

class Post(models.Model):
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE, null=True)
    text = models.TextField(blank=True)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user)

class Resource(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=300, blank=True)
    excerpt = models.TextField(blank=True)
    link = models.CharField(max_length=300, blank=True)
    file = models.FileField(upload_to='files/%Y%m%d', blank=True)
    featured = models.BooleanField(default=False, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)

    def __str__(self):
        return str(self.title)

class Job(models.Model):
    user = models.ForeignKey(User)
    company = models.CharField(max_length=300)
    title = models.CharField(max_length=300)
    excerpt = models.TextField()
    link = models.CharField(max_length=300)
    image = models.FileField(upload_to='images/%Y%m%d')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)

    def __str__(self):
        return str(self.title)


class Profile(models.Model):
    LOCATION = (
        ('Aberdeen', 'Aberdeen'),
        ('Abilene', 'Abilene'),
        ('Akron', 'Akron'),
        ('Albany', 'Albany'),
        ('Albuquerque', 'Albuquerque'),
        ('Alexandria', 'Alexandria'),
        ('Allentown', 'Allentown'),
        ('Amarillo', 'Amarillo'),
        ('Anaheim', 'Anaheim'),
        ('Anchorage', 'Anchorage'),
        ('Ann Arbor', 'Ann Arbor'),
        ('Antioch', 'Antioch'),
        ('Apple Valley', 'Apple Valley'),
        ('Appleton', 'Appleton'),
        ('Arlington', 'Arlington'),
        ('Arvada', 'Arvada'),
        ('Asheville', 'Asheville'),
        ('Athens', 'Athens'),
        ('Atlanta', 'Atlanta'),
        ('Atlantic City', 'Atlantic City'),
        ('Augusta', 'Augusta'),
        ('Aurora', 'Aurora'),
        ('Austin', 'Austin'),
        ('Bakersfield', 'Bakersfield'),
        ('Baltimore', 'Baltimore'),
        ('Barnstable', 'Barnstable'),
        ('Baton Rouge', 'Baton Rouge'),
        ('Beaumont', 'Beaumont'),
        ('Bel Air', 'Bel Air'),
        ('Bellevue', 'Bellevue'),
        ('Berkeley', 'Berkeley'),
        ('Bethlehem', 'Bethlehem'),
        ('Billings', 'Billings'),
        ('Birmingham', 'Birmingham'),
        ('Bloomington', 'Bloomington'),
        ('Boise', 'Boise'),
        ('Boise City', 'Boise City'),
        ('Bonita Springs', 'Bonita Springs'),
        ('Boston', 'Boston'),
        ('Boulder', 'Boulder'),
        ('Bradenton', 'Bradenton'),
        ('Bremerton', 'Bremerton'),
        ('Bridgeport', 'Bridgeport'),
        ('Brighton', 'Brighton'),
        ('Brownsville', 'Brownsville'),
        ('Bryan', 'Bryan'),
        ('Buffalo', 'Buffalo'),
        ('Burbank', 'Burbank'),
        ('Burlington', 'Burlington'),
        ('Cambridge', 'Cambridge'),
        ('Canton', 'Canton'),
        ('Cape Coral', 'Cape Coral'),
        ('Carrollton', 'Carrollton'),
        ('Cary', 'Cary'),
        ('Cathedral City', 'Cathedral City'),
        ('Cedar Rapids', 'Cedar Rapids'),
        ('Champaign', 'Champaign'),
        ('Chandler', 'Chandler'),
        ('Charleston', 'Charleston'),
        ('Charlotte', 'Charlotte'),
        ('Chattanooga', 'Chattanooga'),
        ('Chesapeake', 'Chesapeake'),
        ('Chicago', 'Chicago'),
        ('Chula Vista', 'Chula Vista'),
        ('Cincinnati', 'Cincinnati'),
        ('Clarke County', 'Clarke County'),
        ('Clarksville', 'Clarksville'),
        ('Clearwater', 'Clearwater'),
        ('Cleveland', 'Cleveland'),
        ('College Station', 'College Station'),
        ('Colorado Springs', 'Colorado Springs'),
        ('Columbia', 'Columbia'),
        ('Columbus', 'Columbus'),
        ('Concord', 'Concord'),
        ('Coral Springs', 'Coral Springs'),
        ('Corona', 'Corona'),
        ('Corpus Christi', 'Corpus Christi'),
        ('Costa Mesa', 'Costa Mesa'),
        ('Dallas', 'Dallas'),
        ('Daly City', 'Daly City'),
        ('Danbury', 'Danbury'),
        ('Davenport', 'Davenport'),
        ('Davidson County', 'Davidson County'),
        ('Dayton', 'Dayton'),
        ('Daytona Beach', 'Daytona Beach'),
        ('Deltona', 'Deltona'),
        ('Denton', 'Denton'),
        ('Denver', 'Denver'),
        ('Des Moines', 'Des Moines'),
        ('Detroit', 'Detroit'),
        ('Downey', 'Downey'),
        ('Duluth', 'Duluth'),
        ('Durham', 'Durham'),
        ('El Monte', 'El Monte'),
        ('El Paso', 'El Paso'),
        ('Elizabeth', 'Elizabeth'),
        ('Elk Grove', 'Elk Grove'),
        ('Elkhart', 'Elkhart'),
        ('Erie', 'Erie'),
        ('Escondido', 'Escondido'),
        ('Eugene', 'Eugene'),
        ('Evansville', 'Evansville'),
        ('Fairfield', 'Fairfield'),
        ('Fargo', 'Fargo'),
        ('Fayetteville', 'Fayetteville'),
        ('Fitchburg', 'Fitchburg'),
        ('Flint', 'Flint'),
        ('Fontana', 'Fontana'),
        ('Fort Collins', 'Fort Collins'),
        ('Fort Lauderdale', 'Fort Lauderdale'),
        ('Fort Smith', 'Fort Smith'),
        ('Fort Walton Beach', 'Fort Walton Beach'),
        ('Fort Wayne', 'Fort Wayne'),
        ('Fort Worth', 'Fort Worth'),
        ('Frederick', 'Frederick'),
        ('Fremont', 'Fremont'),
        ('Fresno', 'Fresno'),
        ('Fullerton', 'Fullerton'),
        ('Gainesville', 'Gainesville'),
        ('Garden Grove', 'Garden Grove'),
        ('Garland', 'Garland'),
        ('Gastonia', 'Gastonia'),
        ('Gilbert', 'Gilbert'),
        ('Glendale', 'Glendale'),
        ('Grand Prairie', 'Grand Prairie'),
        ('Grand Rapids', 'Grand Rapids'),
        ('Grayslake', 'Grayslake'),
        ('Green Bay', 'Green Bay'),
        ('GreenBay', 'GreenBay'),
        ('Greensboro', 'Greensboro'),
        ('Greenville', 'Greenville'),
        ('Gulfport-Biloxi', 'Gulfport-Biloxi'),

src/templates/navigation.html
{% load staticfiles %}
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light" id="sidebar">
  <div class="container-fluid">

    <!-- Toggler -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidebarCollapse" aria-controls="sidebarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Brand -->

    <!--<a class="navbar-brand" href="index.html">
      <img src="{% static 'assets/img/logo.png' %}" class="navbar-brand-img 
      mx-auto" alt="...">
    </a>-->
    <a class="navbar-brand" href="{% url 'app:home' %}">
      <div class="avatar avatar-sm">
        <span class="avatar-title rounded-circle bg-dark">VCP</span>
      </div>
    </a>

    <!-- User (xs) -->
    <div class="navbar-user d-md-none">

      <!-- Dropdown -->
      <div class="dropdown">
  
        <!-- Toggle -->
        <a href="#!" id="sidebarIcon" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="avatar avatar-sm avatar-online">
            {% for profile in user.profile_set.all %}
              {% if profile.image %}
              <img src="{{profile.image.url}}" class="avatar-img rounded-circle" alt="...">
              {% else %}
              <img src="{% static 'assets/img/logo.png' %}" class="avatar-img rounded-circle" alt="...">
              {% endif %}
            {% endfor %}
          </div>
        </a>

        <!-- Menu -->
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="sidebarIcon">
          {% for profile in user.profile_set.all %}
          <a href="{% url 'app:info-update' profile.id %}" class="dropdown-item">Account</a>
          {% endfor %}
          <hr class="dropdown-divider">
          <form method="post" action="{% url 'account_logout' %}">
            {% csrf_token %}
            {% if redirect_field_value %}
            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
            {% endif %}
            <button class="dropdown-item" style="cursor:pointer">Logout</button>
          </form>
        </div>

      </div>

    </div>

    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="sidebarCollapse">

      {% if user.is_superuser %}
      
      <!-- Navigation -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#sidebarDashboards" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarDashboards">
            <i class="fe fe-home"></i> Admin
          </a>
          <div class="collapse " id="sidebarDashboards">
            <ul class="nav nav-sm flex-column">
              <li class="nav-item">
                <a href="{% url 'app:members-admin' %}" class="nav-link ">
                  Members
                </a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link ">
                  Partners
                </a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link ">
                  Resources
                </a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link ">
                  Jobs
                </a>
              </li>
            </ul>
          </div>
        </li>
      </ul>

      <!-- Divider -->
      <hr class="navbar-divider my-3">

      {% endif %}

      {% if user.profile_set.all.0.status != 'Active' %}
      <!-- Heading -->
      <h6 class="navbar-heading">
        Navigation
      </h6>
      <ul class="navbar-nav mb-md-4">
        <li class="nav-item">
          <a href="mailto:admin@vcplatform.com" class="nav-link">
            <i class="fe fe-mail"></i> Help
          </a>
        </li>
      </a>
      {% else %}

      <!-- Heading -->
      <h6 class="navbar-heading">
        Navigation
      </h6>

      <!-- Navigation -->
      <ul class="navbar-nav mb-md-4">
        <li class="nav-item">
          {% if request.path == '/home/' %}
          <a href="{% url 'app:home' %}" class="nav-link active">
          {% else %}
          <a href="{% url 'app:home' %}" class="nav-link">
          {% endif %}
            <i class="fe fe-clipboard"></i> Home
          </a>
        </li>
        <li class="nav-item">
          {% if request.path == '/members/' %}
          <a href="{% url 'app:members' %}" class="nav-link active">
          {% else %}
          <a href="{% url 'app:members' %}" class="nav-link">
          {% endif %}
            <i class="fe fe-users"></i> Members
          </a>
        </li>
        <li class="nav-item">
          {% if request.path == '/events/' %}
          <a href="{% url 'app:jobs' %}" class="nav-link active">
          {% else %}
          <a href="{% url 'app:events' %}" class="nav-link">
          {% endif %}
            <i class="fe fe-calendar"></i> Events
          </a>
        </li>
        <li class="nav-item">
          {% if request.path == '/vendors/' %}
          <a href="{% url 'app:vendors' %}" class="nav-link active">
          {% else %}
          <a href="{% url 'app:vendors' %}" class="nav-link">
          {% endif %}
            <i class="fe fe-user-check"></i> Vendors
          </a>
        </li>
        <li class="nav-item">
          {% if request.path == '/jobs/' %}
          <a href="{% url 'app:jobs' %}" class="nav-link active">
          {% else %}
          <a href="{% url 'app:jobs' %}" class="nav-link">
          {% endif %}
            <i class="fe fe-file-text"></i> Jobs
          </a>
        </li>
        <li class="nav-item">
          {% if request.path == '/resources/' %}
          <a href="{% url 'app:resources' %}" class="nav-link active">
          {% else %}
          <a href="{% url 'app:resources' %}" class="nav-link">
          {% endif %}
            <i class="fe fe-folder-plus"></i> Resources
          </a>
        </li>
      </ul>
      {% endif %}

    </div> <!-- / .navbar-collapse -->

  </div>
</nav>

src/templates/post_comment.html
{% load staticfiles %}
{% load humanize %}
<div class="comment mt-5 mb-3" style="width:100%">
  <div class="row">
    <div class="col-auto">

      <!-- Avatar -->
      <a class="avatar avatar-sm" href="{% url 'app:profile' comment.user.username %}">
        {% for profile in comment.user.profile_set.all %}
          {% if profile.image %}
            <img src="{{profile.image.url}}" alt="..." class="avatar-img rounded-circle">
          {% else %}
            <img src="{% static 'assets/img/logo.png' %}" alt="..." class="avatar-img rounded-circle">
          {% endif %}
        {% endfor %}
      </a>

    </div>
    <div class="col ml--2">
      
      <!-- Body -->
      <div class="comment-body w-100">

        <div class="row">
          <div class="col">

            <!-- Title -->
            <h5 class="comment-title">
              <a href="{% url 'app:profile' comment.user.username %}">{{comment.user.first_name}} {{comment.user.last_name}}</a>
            </h5>

          </div>
          <div class="col-auto">

            <!-- Time -->
            <time class="comment-time">
              {% if user == comment.user %}
              <!--<a href=""><i class="fe fe-edit"></i></a>-->
              <a href="#" class="delete-comment" data-toggle="modal" data-target="#delete2" data-id="{{ comment.id }}" ><i class="fe fe-trash"></i></a>
              {% endif %}
              <span class="mr-2"></span>
              <span class="fe fe-clock"></span>
              {{comment.created_at|naturaltime|capfirst}}
            </time>

          </div>
        </div> <!-- / .row -->

        <!-- Text -->
        <p class="comment-text">
          {{comment.text|urlize}}
        </p>

      </div>

    </div>
  </div> <!-- / .row -->
</div>

src/templates/vendors.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block navigation %}
  {% include 'navigation.html' %}
{% endblock %}

{% block content %}
<!-- MAIN CONTENT
================================================== -->
<div class="main-content">
  
  {% include 'navbar.html' %}

  <!-- CONTENT -->
  <div class="container-fluid mt-5 mb-5">
    <div class="row">
      <div class="col-12">
        
        <!-- Files -->
        <div class="card" data-toggle="lists" data-lists-values='["name"]'>
          <div class="card-header">
            <div class="row align-items-center">
              <div class="col">
                
                <!-- Title -->
                <h4 class="card-header-title">
                  Vendors
                </h4>

              </div>
              <div class="col-auto">
                
                <!-- Dropdown -->
                <div class="dropdown">

                  <!-- Toggle -->
                  <a href="#!" class="small text-muted dropdown-toggle" data-toggle="dropdown">
                    Sort order
                  </a>

                  <!-- Menu -->
                  <div class="dropdown-menu">
                    <a class="dropdown-item sort" data-sort="name" href="#!">
                      Asc
                    </a>
                    <a class="dropdown-item sort" data-sort="name" href="#!">
                      Desc
                    </a>
                  </div>

                </div>

              </div>
              <div class="col-auto">
                    
                <!-- Button -->
                <a href="{% url 'app:vendor-create' %}" class="btn btn-sm btn-primary">
                  Post Vendor
                </a>

              </div>
            </div> <!-- / .row -->
          </div>
          <div class="card-header">
            <div class="row">
              <div class="col-12">
                
                <!-- Form -->
                <form>
                  <div class="input-group input-group-flush input-group-merge">
                    <input type="search" class="form-control form-control-prepended search" placeholder="Search">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <span class="fe fe-search"></span>
                      </div>
                    </div>
                  </div>
                </form>

              </div>
            </div> <!-- / .row -->
          </div>
          <div class="card-body">

            <!-- List -->
            <ul class="list-group list-group-lg list-group-flush list my--4">

              {% if not vendors %}
              <li class="list-group-item px-0">
                <div class="row align-items-center">
                    <div class="col-auto">
                      <p>No vendors available.</p>
                    </div>
                </div>
              </li>
              {% endif %}

              {% for vendor in vendors %}
              <li class="list-group-item px-0">
                
                <div class="row align-items-center">
                  <div class="col-auto">
                    
                    <!-- Avatar -->
                    <a class="navbar-brand" href="{% url 'app:home' %}">
                      <div class="avatar avatar-md">
                        <span class="avatar-title rounded-circle">{{vendor.title|first}}</span>
                      </div>
                    </a>

                  </div>
                  <div class="col ml--2">

                    <!-- Title -->
                    <h4 class="card-title mb-1 name">
                      {{vendor.title}}
                      {% if vendor.link %}
                      <a href="{{vendor.link}}" class="text-primary" target="_blank"><span class="fe fe-external-link mr-4"></span></a>
                      {% endif %}
                    </h4>
                    {% for category in vendor.categories %}
                      <span class="badge badge-soft-secondary">{{category}}</span>
                    {% endfor %}
                    

                    <!-- Text -->
                    <p class="card-text small mb-1">
                      {{vendor.description}}<br>Contact: {{vendor.contact}}, <a href="mailto:{{vendor.contact_email}}">{{vendor.contact_email}}</a>
                    </p>

                    <!-- Time -->
                    <p class="card-text small text-muted">
                      Posted by <a href="{% url 'app:profile' vendor.user.username %}">{{vendor.user.first_name}} {{vendor.user.last_name}}</a> on <time datetime="2018-01-03">Jan 3, 2018</time>
                    </p>
                    
                  </div>
                  {% if vendor.user == user %}
                  <div class="col-auto">
                    
                    <!-- Dropdown -->
                    <div class="dropdown">
                      <a href="#!" class="dropdown-ellipses dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fe fe-more-vertical"></i>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right">
                        <a href="{% url 'app:vendor-update' vendor.id %}" class="dropdown-item">
                          Edit
                        </a>
                        <a href="#!" class="dropdown-item delete-vendor" data-toggle="modal" data-target="#delete5" data-id="{{ vendor.id }}">
                          Delete
                        </a>
                      </div>
                    </div>

                  </div>
                  {% endif %}
                </div> <!-- / .row -->

              </li>

              {% endfor %}
            </ul>

          </div>
        </div>

      </div>
    </div> <!-- / .row -->
  </div>
  
</div> <!-- / .main-content -->
<!-- Modal Delete Job -->
<div class="modal fade" id="delete5" tabindex="-1" role="dialog" aria-labelledby="deleteCommentLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body p-4">
          <div class="text-center">
              <i class="fe fe-alert-triangle h1 text-warning"></i>
              <h4 class="mt-2">Delete Vendor</h4>
              <p class="mt-3">Are you sure you want to delete this vendor?</p>
              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
              <button type="button" class="btn btn-danger my-2 text-white" id="delete-vendor-submit" data-dismiss="modal">Delete</button>
          </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}